version: '3.8'
services:
  postgres:
      image: postgres:15.1-bullseye
      ports:
        - 5432:5432
      environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=OpenSesame
        - POSTGRES_DB=shortner
      volumes:
        - '/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock'

  url_shortner_app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://user:OpenSesame@postgres:5432/shortner
      - BASE_URL=https://tier.app/
    ports:
      - 8080:8080
    restart: on-failure
    links:
      - postgres

