[package]
name = "entity"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/mod.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
sea-orm = { version = "0.11.1" }
